### ISSUE TITLE
Cannot read property 'crossOrigin' of undefined

### ISSUE THREAD

**Issue by Hacksore** [yushijinhun/skinview-utils#11]
This doesn't work well on base64 images, is this a bug or a feature 

![image](https://user-images.githubusercontent.com/996134/119409743-5f598b00-bcad-11eb-8970-7d1631358d6a.png)

**Comment by yushijinhun** [comment]
I can't reproduce this bug. Loading base64 cape works fine on Firefox 88. (skinview3d 2.0.1)
