### ISSUE TITLE
Support 46x22 cape texture

### ISSUE THREAD

**Issue by egorprnn** [yushijinhun/skinview-utils#4]
When using optifine capes we get the error: Bad cape size: 92x44.
Why not automatically resize the cape to the correct one?

http://s.optifine.net/capes/Twennnn.png

![image](https://user-images.githubusercontent.com/42776347/77519051-8c07ec00-6eca-11ea-92fd-d0a5ea33b628.png)

**Comment by yushijinhun** [comment]
As is shown below, the given texture(46x22) is a part of a complete cape texture (64x32).

![image](https://user-images.githubusercontent.com/8373027/77606892-b651bc00-6f53-11ea-9261-d0352d89f431.png)
